<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>8.0</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <DebugType>embedded</DebugType>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Version>3.2.0</Version>
    <Authors>dabudi contributors</Authors>
    <RepositoryUrl>https://github.com/v1waa/dabudi</RepositoryUrl>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
