name: Предложение функции
description: Идея улучшения проекта
title: "[Feature]: "
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую задачу нужно решить?
      description: Опишите сценарий и текущее неудобство.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Альтернативы и дополнительный контекст
